// This file is generated by Clarify. Do not edit it manually.
// It provides ambient type declarations for Clarify virtual modules used in
// plugin and slot code, so the TypeScript language service can resolve them.

declare module 'virtual:clarify/slot' {
  import type { UISlotContext } from '@clarify-labs/cli'

  export function useSlot(): UISlotContext
}
